// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.EF;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250624151219_InitialCreate3")]
    partial class InitialCreate3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Business.Models.Conferente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("id");

                    b.ToTable("Conferente", (string)null);
                });

            modelBuilder.Entity("Business.Models.Entrega", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Entregue")
                        .HasColumnType("bit");

                    b.Property<int>("conferenteID")
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<int>("entregadorID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fim")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("inicio")
                        .HasColumnType("datetime");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<double>("valor")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("conferenteID");

                    b.HasIndex("entregadorID");

                    b.ToTable("Entrega", (string)null);
                });

            modelBuilder.Entity("Business.Models.Entregador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("id");

                    b.ToTable("Entregador", (string)null);
                });

            modelBuilder.Entity("Business.Models.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<double>("valor")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("Business.Models.ProdutoEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntregaId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<int?>("Produtoid")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntregaId");

                    b.HasIndex("ProdutoID");

                    b.HasIndex("Produtoid")
                        .IsUnique()
                        .HasFilter("[Produtoid] IS NOT NULL");

                    b.ToTable("ProdutoEntrega", (string)null);
                });

            modelBuilder.Entity("Business.Models.Entrega", b =>
                {
                    b.HasOne("Business.Models.Conferente", "conferente")
                        .WithMany()
                        .HasForeignKey("conferenteID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Business.Models.Entregador", "entregador")
                        .WithMany()
                        .HasForeignKey("entregadorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Business.Models.ProdutoEntrega", "produtoentrega")
                        .WithMany()
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("conferente");

                    b.Navigation("entregador");

                    b.Navigation("produtoentrega");
                });

            modelBuilder.Entity("Business.Models.ProdutoEntrega", b =>
                {
                    b.HasOne("Business.Models.Entrega", "Entrega")
                        .WithMany()
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Business.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Business.Models.Produto", null)
                        .WithOne("produtoentrega")
                        .HasForeignKey("Business.Models.ProdutoEntrega", "Produtoid");

                    b.Navigation("Entrega");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Business.Models.Produto", b =>
                {
                    b.Navigation("produtoentrega")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
